services:
  app:
    build: .
    container_name: storecosts_app
    env_file:
      - .env
    environment:
      - APP_ENV=dev
    volumes:
      - ./app:/app/app
    command: ["python", "-m", "app.main"]
